"""Embed asset semantic descriptions — Phase 2 / Gap 7.5.

Pragmatic choice: at day-1 we use text-embedding-3-small (1536-dim)
on the `semantic_description` field generated by the classify pass.

Why not CLIP/CLAP locally:
- CLIP (vision) and CLAP (audio) embeddings would let us search
  by image/audio similarity rather than text, BUT:
  - they require torch + sentence-transformers + librosa
    (~2 GB of pip packages)
  - they cost CPU minutes per asset for the encode step
  - on the assets we have (CC0 with hand-written descriptions
    and tags) text embedding ALREADY captures the semantics:
    "abandoned bakery 16k HDRI low contrast" embeds fine.
- The migration 003 column embedding_type allows future CLIP/CLAP
  rows alongside text rows. Switching is a backfill, not a schema
  change. So we ship text-only now and revisit when first
  retrieval test shows it's the bottleneck (deferred R.5 in
  blueprint v2 part R).

Output: data/assets_embedded/<library>/manifest.jsonl
The output records carry the embedding as a list[float] (1536 dim)
which 05_store_assets.py converts to pgvector literal at INSERT.

Cost: $0.02 per 1M tokens — typical asset description ~30 tokens
→ ~$0.0006 per 1000 assets. Tiny.
"""
from __future__ import annotations

import argparse
import json
import logging
import os
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from dotenv import load_dotenv

from scripts.ingestion._embed_db import EmbeddingClient
from scripts.ingestion_assets._fetch_helpers import (
    append_jsonl, existing_source_urls, load_jsonl,
)

ASSETS_CLASSIFIED_DIR = REPO_ROOT / "data" / "assets_classified"
ASSETS_EMBEDDED_DIR = REPO_ROOT / "data" / "assets_embedded"
BATCH_SIZE = 100  # OpenAI accepts up to 2048; smaller batch = less waste on failures


def build_embed_text(rec: dict[str, Any]) -> str:
    """Compose the text we embed. Combines the LLM description with
    structural tags so the embedding captures both natural-language
    intent AND taxonomy. Identical pattern to code embeddings where
    we prepend (engine + category) to the chunk body."""
    parts = [
        f"asset_type: {rec.get('asset_type', '')}",
        f"description: {rec.get('semantic_description', '')}",
    ]
    if rec.get("style_pack_compat"):
        parts.append("style_packs: " + ",".join(rec["style_pack_compat"]))
    if rec.get("genre_affinity"):
        parts.append("genres: " + ",".join(rec["genre_affinity"]))
    if rec.get("use_case_tags"):
        parts.append("use_cases: " + ",".join(rec["use_case_tags"]))
    if rec.get("keywords"):
        parts.append("keywords: " + ",".join(rec["keywords"][:15]))
    return " | ".join(parts)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--library",
                    help="Embed only this library (default: all).")
    ap.add_argument("--limit", type=int, default=0)
    ap.add_argument("--force", action="store_true",
                    help="Re-embed records already in the output.")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--verbose", action="store_true")
    args = ap.parse_args()

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(levelname)s %(message)s",
    )
    log = logging.getLogger("embed_assets")
    load_dotenv()

    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        log.error("OPENAI_API_KEY not set")
        return 1

    if not ASSETS_CLASSIFIED_DIR.exists():
        log.error("Run 03_classify_assets.py first.")
        return 1

    libraries = (
        [args.library] if args.library
        else [d.name for d in ASSETS_CLASSIFIED_DIR.iterdir() if d.is_dir()]
    )

    work: list[tuple[str, dict[str, Any]]] = []
    for lib in libraries:
        cls_path = ASSETS_CLASSIFIED_DIR / lib / "manifest.jsonl"
        if not cls_path.exists():
            continue
        already = set() if args.force else existing_source_urls(
            ASSETS_EMBEDDED_DIR / lib / "manifest.jsonl")
        for rec in load_jsonl(cls_path):
            if rec.get("source_url") in already:
                continue
            # Require confidence_score >= 60 (quarantine threshold).
            # Below 60 is rejected, no point spending embedding budget.
            if (rec.get("confidence_score") or 0) < 60:
                continue
            work.append((lib, rec))
            if args.limit and len(work) >= args.limit:
                break
        if args.limit and len(work) >= args.limit:
            break

    log.info("To embed: %d records across %d libraries",
             len(work), len(libraries))
    if args.dry_run or not work:
        return 0

    client = EmbeddingClient(api_key=api_key)
    ASSETS_EMBEDDED_DIR.mkdir(parents=True, exist_ok=True)

    for i in range(0, len(work), BATCH_SIZE):
        batch = work[i:i + BATCH_SIZE]
        texts = [build_embed_text(rec) for _, rec in batch]
        try:
            vectors = client.embed_batch(texts)
        except Exception as exc:
            log.error("Embed batch failed at offset %d: %s", i, exc)
            continue
        if len(vectors) != len(batch):
            log.error("Batch length mismatch: %d != %d",
                      len(vectors), len(batch))
            continue
        for (lib, rec), vec in zip(batch, vectors):
            merged = dict(rec)
            merged["embedding"] = vec
            merged["embedding_type"] = "text"
            append_jsonl(ASSETS_EMBEDDED_DIR / lib / "manifest.jsonl",
                         merged)
        log.info("Embedded %d/%d records",
                 min(i + BATCH_SIZE, len(work)), len(work))

    print("\n" + "=" * 56)
    print("ASSET EMBED SUMMARY")
    print("=" * 56)
    print(f"Requests:     {client.usage.requests}")
    print(f"Input tokens: {client.usage.input_tokens}")
    print(f"Cost USD:     ${client.usage.cost_usd:.4f}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
