"""Catalog seed data — Phase 2 / Gap 8.

Structured Python data extracted from the markdown docs:
  - STYLE_PACK_REFERENCES.md       -> STYLE_PACKS_DATA (30)
  - GAME_REASONING_ENGINE_BLUEPRINT_v2.md §N.3 -> GENRE_TEMPLATES_DATA (14)
  - AUDIO_MOOD_LIBRARY.md          -> AUDIO_MOODS_DATA (12)
  - LORA_LIBRARY_EXPANDED.md       -> LORA_LIBRARY_DATA (~40)
  - REFERENCE_GAMES_VISUAL.md      -> REFERENCE_GAMES_DATA (80)

Each list is consumed by 06_seed_catalogs.py via parameterised
INSERT ... ON CONFLICT DO UPDATE. Editing this file + re-running
the seeder is the canonical way to update a catalog.
"""
from __future__ import annotations

# ============================================================
# STYLE_PACKS_DATA — 30 packs (groups A/B/C/D)
# ============================================================

STYLE_PACKS_DATA: list[dict] = [
    # ----- Group A: Pixel 2D (8) -----
    {
        "id": "A01",
        "display_name": "Pixel Art Dark",
        "description": "Low-bit pixel art with desaturated palette and strong contrast.",
        "group_label": "pixel_2d",
        "palette_hex": ["#140c1c", "#442434", "#30346d", "#4e4a4e",
                        "#854c30", "#346524", "#d04648", "#757161",
                        "#597dce", "#d27d2c", "#8595a1", "#6daa2c"],
        "prompt_modifiers": "pixel art, dark moody, desaturated, retro indie game sprite, sharp pixels, no anti-aliasing",
        "negative_prompt": "blurry, smooth shading, photorealistic, 3d, watercolor, jpeg artifacts",
        "font_family_ui": "VT323",
        "font_family_dialog": "Press Start 2P",
        "music_mood_id": "dark_ambient",
        "sfx_style": "impactful_crunchy",
        "compatible_genres": ["metroidvania", "roguelike", "hardcore_platformer", "bullet_hell"],
        "compatible_engines": ["godot", "monogame", "love2d", "phaser"],
    },
    {
        "id": "A02",
        "display_name": "Pixel Art Vibrant",
        "description": "Saturated pixel art, vivid colors, cozy/positive mood.",
        "group_label": "pixel_2d",
        "palette_hex": ["#1a1c2c", "#5d275d", "#b13e53", "#ef7d57",
                        "#ffcd75", "#a7f070", "#38b764", "#257179",
                        "#29366f", "#3b5dc9", "#41a6f6", "#73eff7",
                        "#f4f4f4", "#94b0c2", "#566c86", "#333c57"],
        "prompt_modifiers": "pixel art, vibrant saturated colors, cheerful, cozy game sprite, clean pixels",
        "negative_prompt": "dark moody, blurry, photorealistic, monochrome, depressing",
        "font_family_ui": "Pixelify Sans",
        "font_family_dialog": "M PLUS Rounded 1c",
        "music_mood_id": "orchestral_calm",
        "sfx_style": "soft_warm",
        "compatible_genres": ["jrpg", "social_sim", "mobile_puzzle"],
        "compatible_engines": ["monogame", "godot", "defold"],
    },
    {
        "id": "A03",
        "display_name": "Pixel Art 1-bit",
        "description": "Only 2 colors (B/W or palette swap), Game Boy tribute.",
        "group_label": "pixel_2d",
        "palette_hex": ["#ffffff", "#000000"],
        "prompt_modifiers": "1-bit pixel art, monochrome, two-color, stark contrast, no greyscale",
        "negative_prompt": "color, grayscale, smooth gradient, soft shading",
        "font_family_ui": "Silkscreen",
        "music_mood_id": "chiptune_arcade",
        "sfx_style": "8bit_chiptune",
        "compatible_genres": ["browser_arcade", "roguelike", "retro_8bit"],
        "compatible_engines": ["love2d", "godot", "defold"],
    },
    {
        "id": "A04",
        "display_name": "Pixel Art GBC",
        "description": "Game Boy Color tribute, 4 tones x 4 palettes.",
        "group_label": "pixel_2d",
        "palette_hex": ["#0f380f", "#306230", "#8bac0f", "#9bbc0f",
                        "#0f3868", "#5878a8", "#80c0f8", "#f8f8f8"],
        "prompt_modifiers": "Game Boy Color style pixel art, limited 4-color palette, retro handheld",
        "negative_prompt": "full RGB, modern lighting, anti-aliased",
        "font_family_ui": "Early GameBoy",
        "music_mood_id": "chiptune_arcade",
        "sfx_style": "8bit_chiptune",
        "compatible_genres": ["jrpg", "retro_8bit"],
        "compatible_engines": ["godot", "monogame"],
    },
    {
        "id": "A05",
        "display_name": "Pixel Art SNES JRPG",
        "description": "Late 90s 16-bit Square JRPG style.",
        "group_label": "pixel_2d",
        "palette_hex": ["#1e1e2c", "#2e3850", "#4860a0", "#6088c0",
                        "#88b0e0", "#ffe8a0", "#ffb060", "#d04030",
                        "#a02020", "#602020", "#404040", "#707070",
                        "#a0a0a0", "#d0d0d0", "#ffffff", "#ffe0d0"],
        "prompt_modifiers": "SNES 16-bit JRPG sprite, classic Square style, top-down RPG, mode 7",
        "negative_prompt": "8-bit blocky, 3d, modern shading",
        "font_family_ui": "Manaspace",
        "font_family_dialog": "PixeloidSans",
        "music_mood_id": "fantasy_celtic",
        "sfx_style": "16bit_warm",
        "compatible_genres": ["jrpg"],
        "compatible_engines": ["monogame", "godot"],
    },
    {
        "id": "A06",
        "display_name": "Pixel Art Cyberpunk",
        "description": "Pixel art with neon magenta/cyan, urban night ambient.",
        "group_label": "pixel_2d",
        "palette_hex": ["#0a0e27", "#1a1f3a", "#ff006e", "#fb5607",
                        "#ffbe0b", "#8338ec", "#3a86ff", "#00f5d4",
                        "#ffffff", "#2d3a5e", "#7209b7", "#f72585"],
        "prompt_modifiers": "cyberpunk pixel art, neon glow, magenta and cyan, urban night, rain, holograms",
        "negative_prompt": "daylight, pastoral, medieval, soft pastel",
        "font_family_ui": "Major Mono Display",
        "font_family_dialog": "VT323",
        "music_mood_id": "synthwave_neon",
        "sfx_style": "synth_glitch",
        "compatible_genres": ["visual_novel", "browser_arcade"],
        "compatible_engines": ["renpy", "godot", "phaser"],
    },
    {
        "id": "A07",
        "display_name": "Pixel Art Horror",
        "description": "Monochrome dark + red/green sickly accents.",
        "group_label": "pixel_2d",
        "palette_hex": ["#0a0a0a", "#1a0a0a", "#2d0a0a", "#4d1010",
                        "#8a0303", "#d40000", "#0a1a0a", "#0a2d0a",
                        "#105510", "#03b403", "#ff7800"],
        "prompt_modifiers": "horror pixel art, dark monochrome, blood red accents, eerie, decayed, cursed",
        "negative_prompt": "cheerful, bright, cute, daylight",
        "font_family_ui": "Special Elite",
        "font_family_dialog": "Creepster",
        "music_mood_id": "dark_ambient",
        "sfx_style": "horror_stinger",
        "compatible_genres": ["visual_novel"],
        "compatible_engines": ["godot", "monogame", "renpy"],
    },
    {
        "id": "A08",
        "display_name": "Pixel Art Arcade Neon",
        "description": "High-contrast 80s arcade pixel art, Hotline Miami vibe.",
        "group_label": "pixel_2d",
        "palette_hex": ["#1a0000", "#ff0096", "#ff6900", "#00fff9",
                        "#fffb00", "#00ff77", "#f200ff", "#000000",
                        "#ffffff"],
        "prompt_modifiers": "neon arcade pixel art, top-down, hotline miami, high contrast, 80s",
        "negative_prompt": "muted, photorealistic, soft",
        "font_family_ui": "Audiowide",
        "font_family_dialog": "VT323",
        "music_mood_id": "synthwave_neon",
        "sfx_style": "synth_glitch",
        "compatible_genres": ["bullet_hell", "browser_arcade", "multiplayer_arena"],
        "compatible_engines": ["godot", "love2d", "phaser"],
    },

    # ----- Group B: Stylized 2D (6) -----
    {
        "id": "B01",
        "display_name": "Flat Cute Vector",
        "description": "Flat vector art, rounded shapes, pastel palette.",
        "group_label": "stylized_2d",
        "palette_hex": ["#ffd6e0", "#ffefd6", "#d6ffea", "#c2e3f5",
                        "#d9c2f5", "#ffffff", "#2d3142", "#4f5d75"],
        "prompt_modifiers": "flat vector art, cute pastel, simple shapes, casual mobile game",
        "negative_prompt": "detailed texture, dark, photorealistic, gritty",
        "font_family_ui": "Quicksand",
        "font_family_dialog": "Nunito",
        "music_mood_id": "tropical_island",
        "sfx_style": "soft_ui",
        "compatible_genres": ["mobile_puzzle", "social_sim"],
        "compatible_engines": ["defold", "phaser", "godot"],
    },
    {
        "id": "B02",
        "display_name": "Hand-Drawn Watercolor",
        "description": "Watercolor / painterly look with soft gradients.",
        "group_label": "stylized_2d",
        "palette_hex": ["#3c2415", "#6b3e2e", "#a86b3c", "#d4a574",
                        "#e8c39e", "#f4dbb5", "#8b7355", "#5a4a3a",
                        "#2d6e5b", "#5fa394"],
        "prompt_modifiers": "watercolor illustration, hand-drawn, soft brush strokes, painterly indie game",
        "negative_prompt": "pixel art, sharp edges, 3d render, photo",
        "font_family_ui": "Caudex",
        "font_family_dialog": "Lora",
        "music_mood_id": "orchestral_calm",
        "sfx_style": "soft_warm",
        "compatible_genres": ["metroidvania"],
        "compatible_engines": ["godot", "monogame"],
    },
    {
        "id": "B03",
        "display_name": "Comic Book Bold",
        "description": "Bold black lines, halftones, flat backgrounds.",
        "group_label": "stylized_2d",
        "palette_hex": ["#000000", "#ffffff", "#ff3a3a", "#ffd900",
                        "#2196f3", "#00c853", "#9c27b0"],
        "prompt_modifiers": "comic book art, bold outlines, halftone dots, flat colors, action pose",
        "negative_prompt": "soft shading, photorealistic, watercolor",
        "font_family_ui": "Bangers",
        "font_family_dialog": "Comic Neue",
        "music_mood_id": "metal_hardcore",
        "sfx_style": "punchy_action",
        "compatible_genres": ["browser_arcade", "multiplayer_arena"],
        "compatible_engines": ["godot", "monogame"],
    },
    {
        "id": "B04",
        "display_name": "Anime VN Soft",
        "description": "Soft anime backgrounds with bloom and character sprite style.",
        "group_label": "stylized_2d",
        "palette_hex": ["#fff5f5", "#ffe5e5", "#ffd9d9", "#ffb8b8",
                        "#d4a5d4", "#b8a5d4", "#5d5d8a", "#2d2d4a",
                        "#ff8a9a"],
        "prompt_modifiers": "anime visual novel, soft bloom, pastel, character sprite art, romantic atmosphere",
        "negative_prompt": "photorealistic, gritty, dark horror, pixel art",
        "font_family_ui": "Zen Maru Gothic",
        "font_family_dialog": "Klee One",
        "music_mood_id": "lofi_chill",
        "sfx_style": "soft_ui",
        "compatible_genres": ["visual_novel", "social_sim"],
        "compatible_engines": ["renpy"],
    },
    {
        "id": "B05",
        "display_name": "Noir Monochrome",
        "description": "Black and white with one accent, hard shadows, film noir.",
        "group_label": "stylized_2d",
        "palette_hex": ["#0a0a0a", "#1a1a1a", "#4a4a4a", "#888888",
                        "#cfcfcf", "#ffffff", "#c41010"],
        "prompt_modifiers": "film noir, monochrome with one red accent, hard contrast, mystery atmosphere",
        "negative_prompt": "colorful, cheerful, pastel, cute",
        "font_family_ui": "Cinzel",
        "font_family_dialog": "Special Elite",
        "music_mood_id": "jazz_noir",
        "sfx_style": "noir_jazz",
        "compatible_genres": ["visual_novel"],
        "compatible_engines": ["renpy", "godot"],
    },
    {
        "id": "B06",
        "display_name": "Paper Craft Collage",
        "description": "Cut-paper look, layered shadows under elements.",
        "group_label": "stylized_2d",
        "palette_hex": ["#f5e9d4", "#e8d5b7", "#d4b89a", "#a8896d",
                        "#856b52", "#5a4634", "#3d2f24", "#e63946",
                        "#2a9d8f", "#f4a261", "#264653"],
        "prompt_modifiers": "paper craft illustration, layered cardstock, fold shadows, hand-cut texture",
        "negative_prompt": "photorealistic, 3d render, digital painting smooth",
        "font_family_ui": "Fredoka",
        "font_family_dialog": "Patrick Hand",
        "music_mood_id": "orchestral_calm",
        "sfx_style": "soft_warm",
        "compatible_genres": ["mobile_puzzle"],
        "compatible_engines": ["godot", "threejs"],
    },

    # ----- Group C: 3D stylized (8) -----
    {
        "id": "C01",
        "display_name": "Low-Poly Cute",
        "description": "Colorful low-poly, no texture, flat shading.",
        "group_label": "stylized_3d",
        "palette_hex": ["#a0e7e5", "#b4f8c8", "#fbe7c6", "#ffaebc",
                        "#ff968a", "#ffcad4", "#c9c9ff", "#efb7ff"],
        "prompt_modifiers": "low poly 3d, cute, flat shading, pastel colors, no textures, indie 3d game",
        "negative_prompt": "high poly, photorealistic, gritty texture, dark",
        "font_family_ui": "Nunito",
        "font_family_dialog": "Quicksand",
        "music_mood_id": "tropical_island",
        "sfx_style": "soft_warm",
        "compatible_genres": ["social_sim", "threejs_showcase"],
        "compatible_engines": ["godot", "threejs", "stride"],
    },
    {
        "id": "C02",
        "display_name": "Voxel Cute",
        "description": "Minecraft-like voxel art with curated palette.",
        "group_label": "stylized_3d",
        "palette_hex": ["#8b5a2b", "#4a9eff", "#ff6b35", "#7fc242"],
        "prompt_modifiers": "voxel art, blocky 3d, minecraft inspired, cute character, curated palette",
        "negative_prompt": "smooth surfaces, photorealistic, high poly",
        "font_family_ui": "Bungee",
        "music_mood_id": "tropical_island",
        "sfx_style": "soft_warm",
        "compatible_genres": ["threejs_showcase", "social_sim"],
        "compatible_engines": ["threejs", "godot"],
    },
    {
        "id": "C03",
        "display_name": "Toon Shaded Anime",
        "description": "Cel-shaded anime, black outlines, 2-3 tone shadows.",
        "group_label": "stylized_3d",
        "palette_hex": ["#fff5e1", "#f4b88f", "#d97a3c", "#8b3a2b",
                        "#2d4a5e", "#4a7c9e", "#b8d4e3"],
        "prompt_modifiers": "cel shaded 3d anime, toon shading, hard black outlines, anime character",
        "negative_prompt": "photorealistic, soft gradient, no outlines",
        "font_family_ui": "M PLUS 1p",
        "music_mood_id": "fantasy_celtic",
        "sfx_style": "punchy_action",
        "compatible_genres": ["stride_action", "jrpg"],
        "compatible_engines": ["stride", "threejs", "godot"],
    },
    {
        "id": "C04",
        "display_name": "PSX Retro 3D",
        "description": "PlayStation 1 style: low-res textures, vertex jitter, fog.",
        "group_label": "stylized_3d",
        "palette_hex": ["#202028", "#3c2c34", "#685058", "#b87858",
                        "#f0d090", "#ffffff"],
        "prompt_modifiers": "PS1 PSX style 3d, low resolution textures, vertex wobble, heavy fog, retro horror",
        "negative_prompt": "modern lighting, smooth surfaces, high resolution textures",
        "font_family_ui": "VCR OSD Mono",
        "music_mood_id": "dark_ambient",
        "sfx_style": "horror_stinger",
        "compatible_genres": ["stride_action", "threejs_showcase"],
        "compatible_engines": ["godot", "threejs", "stride"],
    },
    {
        "id": "C05",
        "display_name": "N64 Soft 3D",
        "description": "Nintendo 64 style: soft polygons, bilinear textures, warm.",
        "group_label": "stylized_3d",
        "palette_hex": ["#c8a878", "#a08858", "#707048", "#604030",
                        "#d0c0a0", "#e8d8b8"],
        "prompt_modifiers": "N64 style 3d, soft polygons, bilinear filtered textures, warm nostalgic",
        "negative_prompt": "high poly, modern PBR, photorealistic",
        "font_family_ui": "Fredoka One",
        "music_mood_id": "fantasy_celtic",
        "sfx_style": "soft_warm",
        "compatible_genres": ["stride_action", "hardcore_platformer"],
        "compatible_engines": ["godot", "stride"],
    },
    {
        "id": "C06",
        "display_name": "Sci-Fi Clean",
        "description": "Clean 3D, metallic/emissive, cool palette + warm accent.",
        "group_label": "stylized_3d",
        "palette_hex": ["#0a0e1a", "#1a2440", "#2a3a5e", "#6080a8",
                        "#a8c4ec", "#ffffff", "#ff8c00", "#00ffaa"],
        "prompt_modifiers": "clean sci-fi 3d, metallic surfaces, emissive lights, minimalist tech",
        "negative_prompt": "rusty, organic, fantasy, cluttered",
        "font_family_ui": "Orbitron",
        "font_family_dialog": "Exo 2",
        "music_mood_id": "electronic_tense",
        "sfx_style": "synth_glitch",
        "compatible_genres": ["threejs_showcase", "stride_action"],
        "compatible_engines": ["stride", "threejs", "godot"],
    },
    {
        "id": "C07",
        "display_name": "Fantasy Stylized 3D",
        "description": "Stylized fantasy 3D, saturated palette, detailed props.",
        "group_label": "stylized_3d",
        "palette_hex": ["#3d2818", "#6b4a2e", "#a87a4c", "#d4b88f",
                        "#ecdab8", "#2d4a3e", "#4a8c64", "#b86fff",
                        "#fec5ff"],
        "prompt_modifiers": "stylized fantasy 3d, painterly textures, hand-painted look, RPG asset",
        "negative_prompt": "photorealistic, sci-fi modern, gritty",
        "font_family_ui": "Cinzel",
        "font_family_dialog": "Crimson Text",
        "music_mood_id": "fantasy_celtic",
        "sfx_style": "epic_orchestral",
        "compatible_genres": ["stride_action", "jrpg"],
        "compatible_engines": ["stride", "godot"],
    },
    {
        "id": "C08",
        "display_name": "Abstract Geometric",
        "description": "Pure geometric shapes, gradients, ambient luminous.",
        "group_label": "stylized_3d",
        "palette_hex": ["#1a1a2e", "#16213e", "#0f3460", "#e94560"],
        "prompt_modifiers": "abstract geometric 3d, gradient backgrounds, neon glow, minimalist puzzle",
        "negative_prompt": "organic, detailed texture, photorealistic",
        "font_family_ui": "Space Grotesk",
        "font_family_dialog": "Inter",
        "music_mood_id": "electronic_tense",
        "sfx_style": "synth_glitch",
        "compatible_genres": ["threejs_showcase", "mobile_puzzle"],
        "compatible_engines": ["threejs", "stride", "godot"],
    },

    # ----- Group D: Experimental (8) -----
    {
        "id": "D01",
        "display_name": "ASCII Roguelike",
        "description": "Pure ASCII characters as sprites.",
        "group_label": "experimental",
        "palette_hex": ["#000000", "#ffffff", "#ff0000", "#00ff00",
                        "#ffff00", "#0000ff", "#ff00ff", "#00ffff"],
        "prompt_modifiers": "ascii art, terminal text rendering, dwarf fortress style",
        "negative_prompt": "graphical sprite, smooth, anti-aliased",
        "font_family_ui": "Cousine",
        "music_mood_id": "dark_ambient",
        "sfx_style": "8bit_chiptune",
        "compatible_genres": ["roguelike"],
        "compatible_engines": ["love2d", "godot", "defold"],
    },
    {
        "id": "D02",
        "display_name": "Hand-Drawn Rotoscope",
        "description": "Rubber-hose / rotoscoped frame-by-frame animation.",
        "group_label": "experimental",
        "palette_hex": ["#f5f3ed", "#d4a574", "#8b6f47", "#2d1810", "#c41e3a"],
        "prompt_modifiers": "1930s rubber hose animation, cuphead style, hand-drawn, vintage cartoon",
        "negative_prompt": "pixel art, 3d, modern anime",
        "font_family_ui": "Yeseva One",
        "music_mood_id": "jazz_noir",
        "sfx_style": "noir_jazz",
        "compatible_genres": ["hardcore_platformer"],
        "compatible_engines": ["godot", "monogame"],
    },
    {
        "id": "D03",
        "display_name": "MS Paint Childlike",
        "description": "Deliberately naive MS Paint aesthetic.",
        "group_label": "experimental",
        "palette_hex": ["#ff0000", "#00ff00", "#0000ff", "#ffff00",
                        "#ff00ff", "#000000"],
        "prompt_modifiers": "MS paint deliberate childlike drawing, naive, pure RGB",
        "negative_prompt": "polished, professional, detailed",
        "font_family_ui": "Comic Neue",
        "music_mood_id": "chiptune_arcade",
        "sfx_style": "8bit_chiptune",
        "compatible_genres": ["visual_novel"],
        "compatible_engines": ["phaser", "godot", "renpy"],
    },
    {
        "id": "D04",
        "display_name": "Gritty Realistic 2D",
        "description": "High-res pixel art with realistic muted tones.",
        "group_label": "experimental",
        "palette_hex": ["#3d3530", "#5a4f44", "#7a6b5c", "#9a8a78",
                        "#b8a895", "#d4c4ad", "#b03020"],
        "prompt_modifiers": "Disco Elysium style painterly 2d, muted realistic, dark fantasy CRPG",
        "negative_prompt": "vibrant, anime, cartoon",
        "font_family_ui": "Cormorant Garamond",
        "font_family_dialog": "EB Garamond",
        "music_mood_id": "jazz_noir",
        "sfx_style": "noir_jazz",
        "compatible_genres": ["visual_novel"],
        "compatible_engines": ["monogame", "godot"],
    },
    {
        "id": "D05",
        "display_name": "VN Photographic",
        "description": "Photographic backgrounds with anime sprites overlay.",
        "group_label": "experimental",
        "palette_hex": ["#3a4a5e", "#5e7088", "#88a0b8", "#c4d0dc", "#f0f4f8"],
        "prompt_modifiers": "photo background with anime character sprites, Steins;Gate style VN",
        "negative_prompt": "fully illustrated, no photo",
        "font_family_ui": "Sawarabi Mincho",
        "font_family_dialog": "Noto Serif JP",
        "music_mood_id": "lofi_chill",
        "sfx_style": "soft_ui",
        "compatible_genres": ["visual_novel"],
        "compatible_engines": ["renpy"],
    },
    {
        "id": "D06",
        "display_name": "Minimalist Mono",
        "description": "Two-color silhouette aesthetic.",
        "group_label": "experimental",
        "palette_hex": ["#0a0a0a", "#f0f0f0"],
        "prompt_modifiers": "silhouette minimalist, two-color, Limbo style atmospheric",
        "negative_prompt": "colorful, detailed, busy",
        "font_family_ui": "Cormorant Garamond",
        "music_mood_id": "dark_ambient",
        "sfx_style": "horror_stinger",
        "compatible_genres": ["hardcore_platformer", "mobile_puzzle"],
        "compatible_engines": ["godot", "phaser", "love2d"],
    },
    {
        "id": "D07",
        "display_name": "Synthwave 80s",
        "description": "Neon retrowave, 80s aesthetic.",
        "group_label": "experimental",
        "palette_hex": ["#0a0a0a", "#1a0033", "#2d0080", "#ff006e",
                        "#fb5607", "#ffbe0b", "#00f5d4"],
        "prompt_modifiers": "synthwave 80s neon, retrowave, sun gradient, grid horizon",
        "negative_prompt": "medieval, pastoral, soft pastel",
        "font_family_ui": "Audiowide",
        "font_family_dialog": "VT323",
        "music_mood_id": "synthwave_neon",
        "sfx_style": "synth_glitch",
        "compatible_genres": ["browser_arcade", "bullet_hell"],
        "compatible_engines": ["godot", "threejs", "phaser"],
    },
    {
        "id": "D08",
        "display_name": "Dark Fantasy Painted",
        "description": "Oil-painted dark fantasy, Berserk/Darkest Dungeon style.",
        "group_label": "experimental",
        "palette_hex": ["#1a0e0a", "#2d1a0e", "#4a2818", "#6e3a24",
                        "#8a5230", "#a87040", "#cfa080", "#9a0c0c"],
        "prompt_modifiers": "dark fantasy oil painting, Darkest Dungeon style, gothic, painterly digital art",
        "negative_prompt": "cheerful, bright, cartoony, pixel art",
        "font_family_ui": "Caudex",
        "font_family_dialog": "Cormorant Garamond",
        "music_mood_id": "epic_orchestral",
        "sfx_style": "epic_orchestral",
        "compatible_genres": ["roguelike", "card_game"],
        "compatible_engines": ["monogame", "godot"],
    },
]


# ============================================================
# GENRE_TEMPLATES_DATA — 14 templates (T01-T14)
# Pacing curve: [intro, build, mid, climax, end] normalized 0..1
# ============================================================

GENRE_TEMPLATES_DATA: list[dict] = [
    {
        "id": "T01",
        "display_name": "Metroidvania Platformer",
        "description": "Interconnected world with ability-gated exploration.",
        "tier": "wow",
        "genre": "metroidvania",
        "sub_genre": "platformer_action",
        "target_engine": "godot",
        "alt_engines": ["monogame"],
        "baseline_world_graph": {
            "zones": [
                {"id": "cave_intro", "type": "intro", "difficulty": 1},
                {"id": "forest_mid", "type": "mid", "difficulty": 3},
                {"id": "ruins_late", "type": "late", "difficulty": 5},
                {"id": "boss_arena", "type": "climax", "difficulty": 7, "boss": True},
                {"id": "reward_room", "type": "epilogue", "difficulty": 1},
            ],
            "edges": [
                {"from": "cave_intro", "to": "forest_mid", "gating": "dash"},
                {"from": "forest_mid", "to": "ruins_late", "gating": "double_jump"},
                {"from": "ruins_late", "to": "boss_arena", "gating": "boss_key"},
                {"from": "boss_arena", "to": "reward_room", "gating": "boss_dead"},
            ],
        },
        "baseline_pacing_curve": [0.2, 0.4, 0.7, 0.9, 0.3],
        "baseline_rules": {
            "hp_range": [100, 500],
            "dmg_range": [10, 50],
            "checkpoint_freq_rooms": [3, 5],
            "duration_minutes": [15, 30],
        },
        "recommended_style_pack_ids": ["A01", "B02"],
        "recommended_audio_mood_ids": ["dark_ambient", "epic_orchestral"],
        "reference_game_ids": [],  # filled by 06 from reference_games table
        "code_template_repos": [
            "https://github.com/KoBeWi/Metroidvania-System",
            "https://github.com/EladKarni/godot4-2d-platformer-template",
        ],
        "engine_specific_hints": {
            "godot": "Use Singleton Autoload for inventory cross-scene, Tilemap Terrains for auto-collision",
        },
    },
    {
        "id": "T02",
        "display_name": "Visual Novel",
        "description": "Branching dialogue narrative with character routes.",
        "tier": "wow",
        "genre": "visual_novel",
        "sub_genre": "dating_sim",
        "target_engine": "renpy",
        "alt_engines": [],
        "baseline_world_graph": {
            "zones": [
                {"id": "prologue", "type": "intro"},
                {"id": "hub_temporal", "type": "mid"},
                {"id": "good_route", "type": "good_branch"},
                {"id": "bad_route", "type": "bad_branch"},
                {"id": "epilogue", "type": "end"},
            ],
            "edges": [
                {"from": "prologue", "to": "hub_temporal"},
                {"from": "hub_temporal", "to": "good_route", "gating": "affection_ge_50"},
                {"from": "hub_temporal", "to": "bad_route", "gating": "affection_lt_20"},
                {"from": "good_route", "to": "epilogue"},
                {"from": "bad_route", "to": "epilogue"},
            ],
        },
        "baseline_pacing_curve": [0.1, 0.3, 0.5, 0.8, 0.2],
        "baseline_rules": {
            "affection_range": [0, 100],
            "dialog_impact_range": [-10, 15],
            "duration_minutes_per_route": [10, 15],
            "autosave_every_n_blocks": [1, 10],
        },
        "recommended_style_pack_ids": ["B04", "A06", "B05"],
        "recommended_audio_mood_ids": ["lofi_chill", "jazz_noir"],
        "code_template_repos": [
            "https://github.com/DRincs-Productions/DS-toolkit",
            "https://github.com/remarkablegames/renpy-template",
        ],
        "engine_specific_hints": {
            "renpy": "Use 'default' for rollback-safe variables, Composite for sprite layering",
        },
    },
    {
        "id": "T03",
        "display_name": "Mobile Casual Puzzle",
        "description": "Grid-based puzzle with progressive difficulty.",
        "tier": "wow",
        "genre": "mobile_puzzle",
        "target_engine": "defold",
        "alt_engines": ["phaser"],
        "baseline_world_graph": {
            "zones": [
                {"id": "tutorial_3x3", "type": "intro"},
                {"id": "grid_5x5", "type": "mid"},
                {"id": "grid_7x7", "type": "late"},
                {"id": "boss_grid", "type": "climax"},
            ],
            "edges": [
                {"from": "tutorial_3x3", "to": "grid_5x5", "gating": "stars_3"},
                {"from": "grid_5x5", "to": "grid_7x7", "gating": "stars_6"},
                {"from": "grid_7x7", "to": "boss_grid", "gating": "stars_15"},
            ],
        },
        "baseline_pacing_curve": [0.4, 0.5, 0.6, 0.9, 0.5],
        "baseline_rules": {
            "moves_range": [15, 30],
            "score_per_match": [100, 500],
            "level_duration_min": [2, 5],
        },
        "recommended_style_pack_ids": ["B01", "B06"],
        "recommended_audio_mood_ids": ["tropical_island", "lofi_chill"],
        "code_template_repos": [
            "https://github.com/Insality/cosmic-dash-jam-2025",
            "https://github.com/Lerg/match3swipe",
        ],
        "engine_specific_hints": {
            "defold": "Collection Proxy for async level unload, msg.post for input routing",
        },
    },
    {
        "id": "T04",
        "display_name": "Browser Arcade",
        "description": "Endless / short-session web arcade with instakill.",
        "tier": "wow",
        "genre": "browser_arcade",
        "target_engine": "phaser",
        "alt_engines": [],
        "baseline_world_graph": {
            "zones": [
                {"id": "title", "type": "intro"},
                {"id": "wave_30s", "type": "mid"},
                {"id": "density_ramp", "type": "late"},
                {"id": "boss_singolare", "type": "climax"},
                {"id": "game_over", "type": "end"},
            ],
            "edges": [
                {"from": "title", "to": "wave_30s", "gating": "click_start"},
                {"from": "wave_30s", "to": "density_ramp", "gating": "score_1000"},
                {"from": "density_ramp", "to": "boss_singolare", "gating": "time_60s"},
                {"from": "boss_singolare", "to": "game_over"},
            ],
        },
        "baseline_pacing_curve": [0.5, 0.7, 0.8, 1.0, 0.0],
        "baseline_rules": {
            "lives_range": [1, 3],
            "instakill": True,
            "duration_minutes": [1, 3],
            "checkpoint": 0,
        },
        "recommended_style_pack_ids": ["A08", "D07"],
        "recommended_audio_mood_ids": ["chiptune_arcade", "synthwave_neon"],
        "code_template_repos": [
            "https://github.com/remarkablegames/phaser-platformer",
        ],
        "engine_specific_hints": {
            "phaser": "Phaser Groups for object pooling, AudioContext unlock on first touch",
        },
    },
    {
        "id": "T05",
        "display_name": "JRPG Top-Down",
        "description": "Turn-based party RPG with overworld + dungeons.",
        "tier": "wow",
        "genre": "jrpg",
        "target_engine": "godot",
        "alt_engines": ["monogame"],
        "baseline_world_graph": {
            "zones": [
                {"id": "city_hub", "type": "intro"},
                {"id": "pianura_transito", "type": "mid"},
                {"id": "dungeon", "type": "late"},
                {"id": "arena_boss", "type": "climax", "boss": True},
                {"id": "santuario_segreto", "type": "optional"},
            ],
            "edges": [
                {"from": "city_hub", "to": "pianura_transito"},
                {"from": "pianura_transito", "to": "dungeon", "gating": "key_item"},
                {"from": "dungeon", "to": "arena_boss", "gating": "ability"},
                {"from": "arena_boss", "to": "santuario_segreto", "gating": "vehicle"},
            ],
        },
        "baseline_pacing_curve": [0.15, 0.4, 0.55, 0.75, 0.95],
        "baseline_rules": {
            "initiative_formula": "speed + RNG(1,20)",
            "damage_formula": "(atk * 1.5) - def",
            "hp_scaling": "hp_base * 1.1^level",
            "inventory_slots": 99,
            "actions_per_turn": 1,
        },
        "recommended_style_pack_ids": ["A05", "A02"],
        "recommended_audio_mood_ids": ["fantasy_celtic", "orchestral_calm"],
        "code_template_repos": [
            "https://github.com/gdquest-demos/godot-open-rpg",
            "https://github.com/bitbrain/pandora",
            "https://github.com/newold3/Godot-RPG-Creator",
            "https://github.com/tuananhcn/Turn-Base-RPG",
            "https://github.com/Ziden/godot-turn-based-rpg",
        ],
        "engine_specific_hints": {
            "godot": "Separate scene tree for map vs battle, Resources for stat databases",
        },
    },
    {
        "id": "T06",
        "display_name": "Card Game Autobattler",
        "description": "Deckbuild + node-graph run, Slay the Spire style.",
        "tier": "wow",
        "genre": "card_game",
        "target_engine": "love2d",
        "alt_engines": ["phaser", "godot"],
        "baseline_world_graph": {
            "zones": [
                {"id": "combat_base", "type": "encounter"},
                {"id": "elite", "type": "encounter_hard"},
                {"id": "campfire", "type": "management"},
                {"id": "merchant", "type": "shop"},
                {"id": "evento_bivio", "type": "choice"},
            ],
            "edges": [
                {"from": "combat_base", "to": "elite"},
                {"from": "elite", "to": "campfire"},
                {"from": "campfire", "to": "merchant"},
                {"from": "merchant", "to": "evento_bivio"},
            ],
        },
        "baseline_pacing_curve": [0.3, 0.5, 0.7, 0.9, 0.4],
        "baseline_rules": {
            "hp_player": 80,
            "mana_per_turn": 3,
            "initial_draw": 5,
            "deck_size_optimal": [20, 25],
            "run_duration_min": [45, 60],
        },
        "recommended_style_pack_ids": ["D08", "A02"],
        "recommended_audio_mood_ids": ["epic_orchestral", "electronic_tense"],
        "code_template_repos": [
            "https://github.com/Cod-e-Codes/CardGame",
            "https://github.com/heisenberg23911/CardGame",
        ],
        "engine_specific_hints": {
            "love2d": "Lua tables as data store, seeded PRNG for reproducible runs",
        },
    },
    {
        "id": "T07",
        "display_name": "Hardcore Platformer",
        "description": "Pixel-perfect platformer with instant respawn.",
        "tier": "wow",
        "genre": "hardcore_platformer",
        "target_engine": "monogame",
        "alt_engines": ["godot"],
        "baseline_world_graph": {
            "zones": [
                {"id": "screen_isolation", "type": "room"},
                {"id": "lato_a", "type": "linear"},
                {"id": "lato_b", "type": "hardcore"},
                {"id": "schermata_sicura", "type": "rest"},
                {"id": "menu_capitoli", "type": "hub"},
            ],
            "edges": [
                {"from": "screen_isolation", "to": "lato_a"},
                {"from": "lato_a", "to": "schermata_sicura"},
                {"from": "lato_a", "to": "lato_b", "gating": "collectible"},
                {"from": "schermata_sicura", "to": "menu_capitoli"},
            ],
        },
        "baseline_pacing_curve": [0.4, 0.6, 0.8, 1.0, 0.3],
        "baseline_rules": {
            "coyote_time_frames": [5, 6],
            "jump_buffer_frames": [4, 5],
            "apex_gravity_multiplier": 0.5,
            "corner_correction_pixels": 4,
            "respawn_time_s": 0.5,
            "failures_per_room": [20, 30],
        },
        "recommended_style_pack_ids": ["A01", "A03"],
        "recommended_audio_mood_ids": ["chiptune_arcade", "metal_hardcore"],
        "code_template_repos": [
            "https://github.com/NoelFB/Celeste",
            "https://github.com/endrealm/Monogame-Platformer-Example",
            "https://github.com/jlauener/MonoPunk",
            "https://github.com/DreamyStranger/MonoGame-Platformer",
        ],
        "engine_specific_hints": {
            "monogame": "AABB discrete collisions, no Box2D/Farseer, direct memory/input",
        },
    },
    {
        "id": "T08",
        "display_name": "Roguelike Dungeon",
        "description": "Procedural dungeons with permadeath runs.",
        "tier": "wow",
        "genre": "roguelike",
        "target_engine": "godot",
        "alt_engines": ["love2d"],
        "baseline_world_graph": {
            "zones": [
                {"id": "hub_centrale", "type": "hub"},
                {"id": "dungeon_base", "type": "mid"},
                {"id": "arena_miniboss", "type": "boss"},
                {"id": "dungeon_avanzato", "type": "late"},
                {"id": "boss_finale", "type": "climax", "boss": True},
            ],
            "edges": [
                {"from": "hub_centrale", "to": "dungeon_base"},
                {"from": "dungeon_base", "to": "arena_miniboss", "gating": "kill_all"},
                {"from": "arena_miniboss", "to": "dungeon_avanzato", "gating": "boss_dead"},
                {"from": "dungeon_avanzato", "to": "boss_finale", "gating": "key"},
            ],
        },
        "baseline_pacing_curve": [0.2, 0.45, 0.7, 1.0, 0.1],
        "baseline_rules": {
            "hp_range": [100, 500],
            "dmg_range": [10, 50],
            "grid_cell_px": [16, 64],
            "aggro_radius_px": [150, 400],
            "run_duration_min": [20, 45],
            "permadeath": True,
        },
        "recommended_style_pack_ids": ["A01", "D01"],
        "recommended_audio_mood_ids": ["dark_ambient", "epic_orchestral"],
        "code_template_repos": [
            "https://github.com/krazyjakee/DungeonTemplateLibrary-Godot",
            "https://github.com/statico/godot-roguelike-example",
        ],
        "engine_specific_hints": {
            "godot": "BSP partition for room layout, A* pathfinding on grid, behavior trees for AI",
        },
    },
    {
        "id": "T09",
        "display_name": "3D Browser Showcase",
        "description": "Interactive 3D scene with click-to-explore.",
        "tier": "wow",
        "genre": "threejs_showcase",
        "target_engine": "threejs",
        "alt_engines": [],
        "baseline_world_graph": {
            "zones": [
                {"id": "pre_loader", "type": "loading"},
                {"id": "hub_espositivo", "type": "hub"},
                {"id": "dettaglio_a", "type": "detail"},
                {"id": "dettaglio_b", "type": "detail"},
            ],
            "edges": [
                {"from": "pre_loader", "to": "hub_espositivo", "gating": "gltf_loaded"},
                {"from": "hub_espositivo", "to": "dettaglio_a", "gating": "click"},
                {"from": "hub_espositivo", "to": "dettaglio_b", "gating": "click"},
            ],
        },
        "baseline_pacing_curve": [0.1, 0.3, 0.5, 0.8, 0.4],
        "baseline_rules": {
            "hp": 1,
            "dmg": 0,
            "camera_fov": [45, 75],
            "raycaster_far": [100, 500],
            "session_min": [5, 10],
        },
        "recommended_style_pack_ids": ["C08", "C04", "C01"],
        "recommended_audio_mood_ids": ["electronic_tense", "orchestral_calm"],
        "code_template_repos": [
            "https://github.com/instructa/viber3d",
            "https://github.com/pmndrs/postprocessing",
            "https://github.com/N8python/n8ao",
            "https://github.com/FarazzShaikh/THREE-CustomShaderMaterial",
        ],
        "engine_specific_hints": {
            "threejs": "EffectComposer pipeline for postprocessing, GLTFLoader async, OrbitControls reset",
        },
    },
    {
        "id": "T10",
        "display_name": "Stride 3D Action",
        "description": "3D action-adventure with weapon upgrades.",
        "tier": "beta",  # Stride OSS ecosystem is sparse
        "genre": "stride_action",
        "target_engine": "stride",
        "alt_engines": [],
        "baseline_world_graph": {
            "zones": [
                {"id": "ambito_tutorial", "type": "intro"},
                {"id": "terreno_overworld", "type": "mid"},
                {"id": "dungeon_meccanico", "type": "puzzle"},
                {"id": "dungeon_organico", "type": "exploration"},
                {"id": "arena_boss", "type": "climax", "boss": True},
            ],
            "edges": [
                {"from": "ambito_tutorial", "to": "terreno_overworld"},
                {"from": "terreno_overworld", "to": "dungeon_meccanico", "gating": "trigger"},
                {"from": "dungeon_meccanico", "to": "dungeon_organico", "gating": "destroy_mesh"},
                {"from": "dungeon_organico", "to": "arena_boss", "gating": "inventory_key"},
            ],
        },
        "baseline_pacing_curve": [0.3, 0.45, 0.65, 1.0, 0.2],
        "baseline_rules": {
            "hp_range": [100, 1000],
            "dmg_range": [15, 100],
            "gravity_y": [-9.8, -15.0],
            "dodge_cooldown_ms": [500, 1200],
            "checkpoint_min": [10, 15],
            "run_minutes": [600, 1200],
        },
        "recommended_style_pack_ids": ["C07", "C03"],
        "recommended_audio_mood_ids": ["epic_orchestral", "fantasy_celtic"],
        "code_template_repos": [],  # Stride OSS strutturalmente esaurito
        "engine_specific_hints": {
            "stride": "BETA TIER: requires manual scaffolding, OSS ecosystem limited",
        },
    },
    {
        "id": "T11",
        "display_name": "Multiplayer Arena",
        "description": "Real-time 2D arena with Nakama backend.",
        "tier": "wow",
        "genre": "multiplayer_arena",
        "target_engine": "godot",
        "alt_engines": [],
        "baseline_world_graph": {
            "zones": [
                {"id": "auth", "type": "login"},
                {"id": "matchmaker_lobby", "type": "queue"},
                {"id": "arena_chiusa", "type": "match"},
            ],
            "edges": [
                {"from": "auth", "to": "matchmaker_lobby", "gating": "jwt_valid"},
                {"from": "matchmaker_lobby", "to": "arena_chiusa", "gating": "queue_filled"},
            ],
        },
        "baseline_pacing_curve": [0.1, 0.5, 0.7, 1.0, 0.0],
        "baseline_rules": {
            "hp_range": [1000, 3000],
            "dmg_range": [50, 300],
            "network_tick_hz": [20, 60],
            "max_players": [4, 16],
            "respawn_s": [3, 5],
            "checkpoint": 0,
        },
        "recommended_style_pack_ids": ["A08", "C06"],
        "recommended_audio_mood_ids": ["metal_hardcore", "electronic_tense"],
        "code_template_repos": [
            "https://github.com/RGonzalezTech/Friendslop-Template",
            "https://github.com/heroiclabs/nakama-project-template",
        ],
        "engine_specific_hints": {
            "godot": "MultiplayerSpawner on match_id, server-side RPC validation",
        },
    },
    {
        "id": "T12",
        "display_name": "Social Sim Generative Agents",
        "description": "NPC town with daily cycle and LLM-driven personalities.",
        "tier": "wow",
        "genre": "social_sim",
        "target_engine": "godot",
        "alt_engines": [],
        "baseline_world_graph": {
            "zones": [
                {"id": "hub_residenziale", "type": "spawn"},
                {"id": "piazza_centrale", "type": "social"},
                {"id": "area_lavorativa", "type": "work"},
                {"id": "mercato_locale", "type": "shop"},
                {"id": "area_riservata", "type": "vip"},
            ],
            "edges": [
                {"from": "hub_residenziale", "to": "piazza_centrale"},
                {"from": "piazza_centrale", "to": "area_lavorativa", "gating": "tool"},
                {"from": "piazza_centrale", "to": "mercato_locale", "gating": "currency"},
                {"from": "piazza_centrale", "to": "area_riservata", "gating": "affinity_80"},
            ],
        },
        "baseline_pacing_curve": [0.20, 0.50, 0.40, 0.90, 0.10],
        "baseline_rules": {
            "energy_social_range": [0, 100],
            "sentiment_range": [-20, 20],
            "checkpoint_per_cycle": 1,
            "session_min": [10, 20],
            "context_token_range": [512, 2048],
        },
        "recommended_style_pack_ids": ["A02", "B01", "A04"],
        "recommended_audio_mood_ids": ["lofi_chill", "orchestral_calm"],
        "code_template_repos": [
            "https://github.com/code-forge-temple/local-llm-npc",
            "https://github.com/nthnn/noko",
            "https://github.com/af009/fuku",
        ],
        "engine_specific_hints": {
            "godot": "Ollama HTTP call non-blocking via threading, sentiment parser to int",
        },
    },
    {
        "id": "T13",
        "display_name": "Bullet Hell",
        "description": "Vertical-scroll danmaku with pattern-based bullets.",
        "tier": "wow",
        "genre": "bullet_hell",
        "target_engine": "love2d",
        "alt_engines": ["godot", "phaser"],
        "baseline_world_graph": {
            "zones": [
                {"id": "fase_iniziale", "type": "intro"},
                {"id": "mid_boss", "type": "boss_mid"},
                {"id": "sciame_proiettili", "type": "mid"},
                {"id": "boss_finale_f1", "type": "boss_f1"},
                {"id": "boss_finale_f2", "type": "boss_f2"},
            ],
            "edges": [
                {"from": "fase_iniziale", "to": "mid_boss", "gating": "timer_30s"},
                {"from": "mid_boss", "to": "sciame_proiettili", "gating": "hp_zero"},
                {"from": "sciame_proiettili", "to": "boss_finale_f1"},
                {"from": "boss_finale_f1", "to": "boss_finale_f2", "gating": "turret_dead"},
            ],
        },
        "baseline_pacing_curve": [0.20, 0.60, 0.40, 1.0, 0.0],
        "baseline_rules": {
            "lives": [1, 3],
            "hitbox_px": 1,
            "dmg_per_frame": [1, 5],
            "no_rng_dmg": True,
            "max_bullets": [1000, 5000],
            "duration_s_per_level": [120, 180],
        },
        "recommended_style_pack_ids": ["A08", "D07"],
        "recommended_audio_mood_ids": ["chiptune_arcade", "metal_hardcore"],
        "code_template_repos": [
            "https://github.com/srijan-paul/bullet_hell",
        ],
        "engine_specific_hints": {
            "love2d": "love.graphics.newSpriteBatch for >1k bullets, sin/cos for spiral patterns",
        },
    },
    {
        "id": "T14",
        "display_name": "Retro 8-bit Restricted",
        "description": "Deliberate retro constraints (palette/resolution/audio).",
        "tier": "wow",
        "genre": "retro_8bit",
        "target_engine": "godot",
        "alt_engines": ["love2d"],
        "baseline_world_graph": {
            "zones": [
                {"id": "schermata_avvio", "type": "intro"},
                {"id": "abisso_platform", "type": "platform"},
                {"id": "stanza_potenziamento", "type": "powerup"},
                {"id": "corridoio_sigillato", "type": "lock"},
                {"id": "arena_boss", "type": "climax", "boss": True},
            ],
            "edges": [
                {"from": "schermata_avvio", "to": "abisso_platform"},
                {"from": "abisso_platform", "to": "stanza_potenziamento"},
                {"from": "stanza_potenziamento", "to": "corridoio_sigillato", "gating": "powerup"},
                {"from": "corridoio_sigillato", "to": "arena_boss"},
            ],
        },
        "baseline_pacing_curve": [0.20, 0.50, 0.80, 1.0, 0.0],
        "baseline_rules": {
            "palette_size_max": 16,
            "resolution_options": ["160x144", "320x240"],
            "hp_points": [1, 6],
            "audio_hz_max": [11025, 22050],
            "checkpoint_per_level": 1,
        },
        "recommended_style_pack_ids": ["A04", "A03", "D06"],
        "recommended_audio_mood_ids": ["chiptune_arcade"],
        "code_template_repos": [
            "https://github.com/ahopness/GodotRetro",
            "https://github.com/glennDittmann/godot-pixel-art-template",
            "https://github.com/MaxiimPetrov/Divine-Retribution-8-bit-Project",
        ],
        "engine_specific_hints": {
            "godot": "Nearest filter, sub-pixel rendering off, AudioEffectBitCrush on Master bus",
        },
    },
]


# ============================================================
# AUDIO_MOODS_DATA — 12 mood baselines
# ============================================================

AUDIO_MOODS_DATA: list[dict] = [
    {
        "id": "epic_orchestral",
        "display_name": "Epic Orchestral",
        "description": "Full orchestra for boss fights and climactic moments.",
        "bpm_min": 90, "bpm_max": 160,
        "key_musical": "D minor",
        "instruments": ["full_orchestra", "brass", "choir", "taiko_drums"],
        "suno_prompts": [
            "Epic orchestral battle theme, full orchestra with brass section, choir vocals, taiko drums, building tension, key of D minor, duration 90 seconds, looping",
            "Heroic orchestral fanfare, French horns, strings, percussion crescendo, victory key C major, 120 BPM, 60 second loop",
        ],
        "layering_pattern": {
            "layer_1_intro": "strings + horn",
            "layer_2_build": "add percussion + choir",
            "layer_3_climax": "full orchestra + brass spike",
        },
        "sfx_freesound_queries": ["sword clash", "magic spell impact", "boss roar", "epic drum hit"],
        "sfx_kenney_packs": ["impact-sounds", "rpg-audio"],
        "template_ids": ["T01", "T05", "T07", "T08", "T10"],
        "style_pack_ids": ["A01", "B02", "C07", "D08"],
    },
    {
        "id": "dark_ambient",
        "display_name": "Dark Ambient",
        "description": "Drone-based atmospheric tension for horror and exploration.",
        "bpm_min": 50, "bpm_max": 70,
        "key_musical": "C minor / F# minor",
        "instruments": ["synth_pad", "processed_strings", "reverse_choir", "field_recording"],
        "suno_prompts": [
            "Dark ambient drone, deep synth pad, reverse choir whispers, industrial low rumble, no melody, atmospheric tension, duration 60 seconds, seamless loop",
        ],
        "layering_pattern": {
            "layer_1": "drone constant",
            "layer_2_event": "whisper pulse + distant scream",
            "layer_3_chase": "faster drone modulation",
        },
        "sfx_freesound_queries": ["horror ambient", "drone dark", "footstep stone", "monster breath"],
        "sfx_kenney_packs": [],
        "template_ids": ["T01", "T07", "T08"],
        "style_pack_ids": ["A01", "A07", "C04", "D01", "D06"],
    },
    {
        "id": "chiptune_arcade",
        "display_name": "Chiptune Arcade",
        "description": "Fast 8-bit NES-style music for arcade games.",
        "bpm_min": 130, "bpm_max": 180,
        "key_musical": "C major / A minor",
        "instruments": ["square_wave", "triangle_wave", "noise_drums"],
        "suno_prompts": [
            "Chiptune 8-bit arcade game music, NES style, fast tempo 150bpm, square wave melody + triangle bass + noise drums, energetic, duration 60 seconds, seamless loop",
        ],
        "layering_pattern": {"boss_key_shift_semitones": -2},
        "sfx_freesound_queries": ["8-bit coin", "8-bit jump", "8-bit hit", "chiptune powerup"],
        "sfx_kenney_packs": ["digital-audio", "interface-sounds"],
        "template_ids": ["T04", "T13", "T14"],
        "style_pack_ids": ["A03", "A04", "A08", "D03"],
    },
    {
        "id": "lofi_chill",
        "display_name": "Lofi Chill",
        "description": "Relaxed lofi hip hop for VN and social sim.",
        "bpm_min": 70, "bpm_max": 90,
        "key_musical": "C major with jazz chords",
        "instruments": ["vinyl_crackle", "jazz_piano", "soft_drums", "mellow_bass"],
        "suno_prompts": [
            "Lofi chill hip hop beat, jazzy piano, vinyl crackle, soft drums, rain ambience background, key of C major, 80bpm, relaxed mood, duration 90 seconds, looping",
        ],
        "layering_pattern": {},
        "sfx_freesound_queries": ["vinyl crackle", "rain ambient", "cafe ambience", "lofi piano"],
        "sfx_kenney_packs": [],
        "template_ids": ["T02", "T03", "T12"],
        "style_pack_ids": ["B01", "B04", "D05"],
    },
    {
        "id": "synthwave_neon",
        "display_name": "Synthwave Neon",
        "description": "80s retrowave for cyberpunk and arcade.",
        "bpm_min": 100, "bpm_max": 130,
        "key_musical": "F# minor / B minor",
        "instruments": ["analog_synth_lead", "gated_reverb_drums", "sidechain_bass", "arpeggio"],
        "suno_prompts": [
            "Synthwave 80s retro neon, analog synthesizer lead, gated reverb snare, side-chained bass, arpeggio synth, F# minor, 110bpm, cinematic, duration 90 seconds, looping",
        ],
        "layering_pattern": {},
        "sfx_freesound_queries": ["laser sci-fi", "neon hum", "glitch ui", "electronic impact"],
        "sfx_kenney_packs": ["sci-fi-sounds"],
        "template_ids": ["T04", "T13"],
        "style_pack_ids": ["A06", "A08", "D07"],
    },
    {
        "id": "orchestral_calm",
        "display_name": "Orchestral Calm",
        "description": "Peaceful orchestral for exploration and towns.",
        "bpm_min": 60, "bpm_max": 90,
        "key_musical": "C / G / D major",
        "instruments": ["solo_flute", "oboe", "soft_strings", "harp"],
        "suno_prompts": [
            "Calm orchestral ambient music, solo flute melody, soft string pad, gentle harp arpeggio, key of C major, 75bpm, peaceful, no percussion, duration 90 seconds, looping",
        ],
        "layering_pattern": {},
        "sfx_freesound_queries": ["wind", "birds chirp", "water gentle", "footstep grass"],
        "sfx_kenney_packs": [],
        "template_ids": ["T01", "T05", "T09"],
        "style_pack_ids": ["A02", "B02", "B06", "C01"],
    },
    {
        "id": "jazz_noir",
        "display_name": "Jazz Noir",
        "description": "Smoky jazz for detective and noir VN.",
        "bpm_min": 80, "bpm_max": 100,
        "key_musical": "D minor / G minor (7th chords)",
        "instruments": ["muted_trumpet", "brushed_drums", "walking_bass", "sax"],
        "suno_prompts": [
            "Jazz noir detective theme, muted trumpet melody, walking bass, brushed drums, minor seventh chords, smoky bar atmosphere, 90bpm, duration 75 seconds, looping",
        ],
        "layering_pattern": {},
        "sfx_freesound_queries": ["cigarette light", "rain on window", "typewriter", "vintage phone"],
        "sfx_kenney_packs": [],
        "template_ids": ["T02"],
        "style_pack_ids": ["B05", "D02", "D04"],
    },
    {
        "id": "fantasy_celtic",
        "display_name": "Fantasy Celtic",
        "description": "Tavern/folk for RPG villages and journey themes.",
        "bpm_min": 90, "bpm_max": 120,
        "key_musical": "D mixolydian / E minor",
        "instruments": ["tin_whistle", "bouzouki", "bodhran", "fiddle", "harp", "accordion"],
        "suno_prompts": [
            "Celtic fantasy tavern music, tin whistle melody, bodhran drum, bouzouki and harp, key of D mixolydian, 110bpm, lively pub atmosphere, duration 90 seconds, looping",
        ],
        "layering_pattern": {},
        "sfx_freesound_queries": ["tankard clink", "fire crackle", "crowd chatter tavern", "sword sheath"],
        "sfx_kenney_packs": [],
        "template_ids": ["T05", "T08", "T10"],
        "style_pack_ids": ["A05", "C03", "C05", "C07"],
    },
    {
        "id": "electronic_tense",
        "display_name": "Electronic Tense",
        "description": "Tense electronic for stealth and sci-fi.",
        "bpm_min": 100, "bpm_max": 140,
        "key_musical": "F minor / A minor",
        "instruments": ["synth_bass_deep", "glitch_percussion", "vocal_chops", "sub_bass"],
        "suno_prompts": [
            "Electronic tense stealth music, deep synth bass, glitch percussion, pulsing sub bass, A minor, 115bpm, suspenseful, cinematic, duration 75 seconds, looping",
        ],
        "layering_pattern": {},
        "sfx_freesound_queries": ["heartbeat", "sneak step", "alert beep", "tension drone"],
        "sfx_kenney_packs": [],
        "template_ids": ["T06", "T11"],
        "style_pack_ids": ["C06", "C08"],
    },
    {
        "id": "piano_emotional",
        "display_name": "Piano Emotional",
        "description": "Solo piano for emotional moments and endings.",
        "bpm_min": 60, "bpm_max": 80,
        "key_musical": "Eb major / F minor",
        "instruments": ["solo_piano", "soft_strings"],
        "suno_prompts": [
            "Emotional solo piano theme, soft felt piano, gentle string pad in background, key of Eb major, 72bpm, melancholic, romantic, duration 90 seconds, looping",
        ],
        "layering_pattern": {},
        "sfx_freesound_queries": ["heartbeat soft", "breath", "rain soft", "paper rustle"],
        "sfx_kenney_packs": [],
        "template_ids": ["T02", "T05", "T12"],
        "style_pack_ids": ["B02", "B05", "D04"],
    },
    {
        "id": "metal_hardcore",
        "display_name": "Metal Hardcore",
        "description": "Aggressive metal for boss fights and bullet hell.",
        "bpm_min": 140, "bpm_max": 200,
        "key_musical": "E phrygian / D minor",
        "instruments": ["distorted_guitar", "double_bass_drums", "growl_vocals", "synth_lead"],
        "suno_prompts": [
            "Heavy metal boss fight music, distorted electric guitar, fast double bass drums, screaming lead, E phrygian, 170bpm, aggressive, duration 75 seconds, looping",
        ],
        "layering_pattern": {},
        "sfx_freesound_queries": ["scream enemy", "explosion metal", "saw clash", "guitar power chord"],
        "sfx_kenney_packs": ["impact-sounds"],
        "template_ids": ["T07", "T08", "T11", "T13"],
        "style_pack_ids": ["A01", "B03", "D08"],
    },
    {
        "id": "tropical_island",
        "display_name": "Tropical Island",
        "description": "Casual tropical for mobile and cozy games.",
        "bpm_min": 100, "bpm_max": 120,
        "key_musical": "C major / G major",
        "instruments": ["ukulele", "steel_drum", "marimba", "soft_percussion", "whistle"],
        "suno_prompts": [
            "Tropical island ukulele music, steel drum, marimba, soft beach percussion, whistle melody, key of C major, 110bpm, happy, duration 75 seconds, looping",
        ],
        "layering_pattern": {},
        "sfx_freesound_queries": ["wave gentle", "seagull", "splash water", "sand step"],
        "sfx_kenney_packs": [],
        "template_ids": ["T03"],
        "style_pack_ids": ["B01", "C01", "C02"],
    },
]


# ============================================================
# LORA_LIBRARY_DATA — verified LoRA models
# ============================================================

LORA_LIBRARY_DATA: list[dict] = [
    # Pixel sprites
    {"hf_repo": "nerijs/pixel-art-xl", "display_name": "Pixel Art XL", "license": "creativeml-openrail-m",
     "base_model": "SDXL-1.0", "trigger_words": ["pixel art"],
     "style_pack_ids": ["A01", "A02", "A03", "A04", "A05", "A06", "A07", "A08"],
     "asset_types": ["sprite", "tileset"], "genre_affinity": ["metroidvania", "jrpg", "hardcore_platformer", "roguelike", "bullet_hell"],
     "tool_affinity": ["sprite_gen", "tileset_gen"],
     "semantic_description": "Workhorse pixel art LoRA for sprite generation. 8.5k downloads, openrail-m commercial OK.",
     "quality_score": 5, "huggingface_downloads": 8571},
    {"hf_repo": "nerijs/pixel-art-3.5L", "display_name": "Pixel Art 3.5L", "license": "apache-2.0",
     "base_model": "SD-3.5", "trigger_words": ["pixel art"],
     "style_pack_ids": ["A01", "A02", "A03"], "asset_types": ["sprite"], "tool_affinity": ["sprite_gen"],
     "semantic_description": "Next-gen pixel art on SD 3.5, higher quality.",
     "quality_score": 4, "huggingface_downloads": 209},
    {"hf_repo": "artificialguybr/PixelArtRedmond", "display_name": "Pixel Art Redmond", "license": "creativeml-openrail-m",
     "base_model": "SDXL-1.0", "trigger_words": ["Pixel Art"],
     "style_pack_ids": ["A05"], "asset_types": ["sprite"], "genre_affinity": ["jrpg"],
     "tool_affinity": ["sprite_gen"],
     "semantic_description": "Alternative pixel art LoRA for 16-bit JRPG style.",
     "quality_score": 4, "huggingface_downloads": 370},
    # Painterly
    {"hf_repo": "ostris/watercolor_style_lora_sdxl", "display_name": "Watercolor Style",
     "license": "apache-2.0", "base_model": "SDXL-1.0", "trigger_words": ["watercolor style"],
     "style_pack_ids": ["B02"], "asset_types": ["background", "concept_art"],
     "genre_affinity": ["metroidvania"], "tool_affinity": ["background_gen", "concept_art_gen"],
     "semantic_description": "Watercolor painterly look, apache-2.0 (cleanest license).",
     "quality_score": 5, "huggingface_downloads": 421},
    {"hf_repo": "nerijs/dark-fantasy-illustration-flux", "display_name": "Dark Fantasy Illustration",
     "license": "mit", "base_model": "FLUX.1-dev", "trigger_words": ["dark fantasy illustration"],
     "style_pack_ids": ["D08"], "asset_types": ["concept_art", "background"],
     "genre_affinity": ["roguelike", "card_game"], "tool_affinity": ["concept_art_gen", "background_gen"],
     "semantic_description": "Darkest Dungeon style dark fantasy painting on FLUX.",
     "quality_score": 5, "huggingface_downloads": 211},
    {"hf_repo": "nerijs/pastelcomic-flux", "display_name": "Pastel Comic Flux", "license": "mit",
     "base_model": "FLUX.1-dev", "trigger_words": ["pastel comic"],
     "style_pack_ids": ["B03"], "asset_types": ["sprite", "background"],
     "tool_affinity": ["sprite_gen", "background_gen"],
     "semantic_description": "Soft comic / cozy narrative style on FLUX.",
     "quality_score": 4, "huggingface_downloads": 169},
    {"hf_repo": "ostris/crayon_style_lora_sdxl", "display_name": "Crayon Style", "license": "apache-2.0",
     "base_model": "SDXL-1.0", "trigger_words": ["crayon"],
     "style_pack_ids": ["B06", "D03"], "asset_types": ["sprite", "background"],
     "tool_affinity": ["sprite_gen", "background_gen"],
     "semantic_description": "Children's drawing crayon aesthetic.",
     "quality_score": 4, "huggingface_downloads": 353},
    {"hf_repo": "artificialguybr/analogredmond-v2", "display_name": "Analog Redmond v2",
     "license": "creativeml-openrail-m", "base_model": "SDXL-1.0", "trigger_words": ["AnalogRedmAF", "analog"],
     "style_pack_ids": ["D04"], "asset_types": ["concept_art"],
     "tool_affinity": ["concept_art_gen"],
     "semantic_description": "Analog/film-grain painterly look for Disco Elysium vibe.",
     "quality_score": 4, "huggingface_downloads": 40},
    {"hf_repo": "goofyai/Leonardo_Ai_Style_Illustration", "display_name": "Leonardo Style Illustration",
     "license": "apache-2.0", "base_model": "SDXL-1.0", "trigger_words": ["leonardo style"],
     "style_pack_ids": [], "asset_types": ["concept_art", "background"],
     "tool_affinity": ["concept_art_gen"],
     "semantic_description": "High-quality generic illustration fallback.",
     "quality_score": 4, "huggingface_downloads": 156},
    {"hf_repo": "nerijs/animation2k-flux", "display_name": "Animation 2K Flux", "license": "mit",
     "base_model": "FLUX.1-dev", "trigger_words": ["animation"],
     "style_pack_ids": ["D02"], "asset_types": ["sprite"], "tool_affinity": ["sprite_gen"],
     "semantic_description": "Smooth 2D animation style on FLUX, rotoscope-ish.",
     "quality_score": 4, "huggingface_downloads": 102},
    # Anime / manga
    {"hf_repo": "Linaqruf/anime-detailer-xl-lora", "display_name": "Anime Detailer XL",
     "license": "openrail++", "base_model": "SDXL-1.0", "trigger_words": ["anime"],
     "style_pack_ids": ["B04"], "asset_types": ["sprite", "background"],
     "genre_affinity": ["visual_novel"], "tool_affinity": ["sprite_gen"],
     "semantic_description": "Anime sprite generation for visual novels.",
     "quality_score": 5, "huggingface_downloads": 3099},
    {"hf_repo": "Linaqruf/style-enhancer-xl-lora", "display_name": "Style Enhancer XL",
     "license": "openrail++", "base_model": "SDXL-1.0", "trigger_words": [],
     "style_pack_ids": ["B04"], "asset_types": ["sprite"], "tool_affinity": ["sprite_gen"],
     "semantic_description": "Stacks with anime detailer for stronger VN aesthetic.",
     "quality_score": 4, "huggingface_downloads": 2944},
    {"hf_repo": "artificialguybr/LineAniRedmond-LinearMangaSDXL-V2", "display_name": "Line Ani Redmond V2",
     "license": "creativeml-openrail-m", "base_model": "SDXL-1.0", "trigger_words": ["LineAniAF", "manga"],
     "style_pack_ids": ["B04"], "asset_types": ["sprite"], "tool_affinity": ["dialogue_gen", "sprite_gen"],
     "semantic_description": "Manga line-art for VN cutscenes.",
     "quality_score": 4, "huggingface_downloads": 174},
    # 3D render
    {"hf_repo": "goofyai/3d_render_style_xl", "display_name": "3D Render Style XL",
     "license": "apache-2.0", "base_model": "SDXL-1.0", "trigger_words": ["3d render"],
     "style_pack_ids": ["C01", "C03", "C07"], "asset_types": ["concept_art"],
     "tool_affinity": ["concept_art_gen"],
     "semantic_description": "Stylized 3D render concept art on SDXL.",
     "quality_score": 5, "huggingface_downloads": 462},
    {"hf_repo": "goofyai/3D_Render_for_Flux", "display_name": "3D Render Flux", "license": "apache-2.0",
     "base_model": "FLUX.1-dev", "trigger_words": ["3d render"],
     "style_pack_ids": ["C01", "C03", "C07"], "asset_types": ["concept_art"],
     "tool_affinity": ["concept_art_gen"],
     "semantic_description": "3D render concept on FLUX, higher quality.",
     "quality_score": 4, "huggingface_downloads": 22},
    {"hf_repo": "goofyai/cyborg_style_xl", "display_name": "Cyborg Style XL", "license": "apache-2.0",
     "base_model": "SDXL-1.0", "trigger_words": ["cyborg"],
     "style_pack_ids": ["C06"], "asset_types": ["concept_art"],
     "tool_affinity": ["concept_art_gen"],
     "semantic_description": "Sci-fi cyborg/mech concept art.",
     "quality_score": 4, "huggingface_downloads": 210},
    {"hf_repo": "jbilcke-hf/sdxl-zelda64", "display_name": "Zelda 64", "license": "creativeml-openrail-m",
     "base_model": "SDXL-1.0", "trigger_words": ["zelda64 style"],
     "style_pack_ids": ["C05"], "asset_types": ["concept_art"], "tool_affinity": ["concept_art_gen"],
     "semantic_description": "N64 Zelda-style 3D vibe.",
     "quality_score": 4, "huggingface_downloads": 76},
    {"hf_repo": "nerijs/lego-minifig-xl", "display_name": "LEGO Minifig XL", "license": "apache-2.0",
     "base_model": "SDXL-1.0", "trigger_words": ["lego minifig"],
     "style_pack_ids": ["C02"], "asset_types": ["sprite"], "tool_affinity": ["sprite_gen"],
     "semantic_description": "LEGO-style toy figures, voxel-adjacent.",
     "quality_score": 4, "huggingface_downloads": 57},
    {"hf_repo": "nerijs/lego-brickheadz-xl", "display_name": "LEGO Brickheadz XL", "license": "apache-2.0",
     "base_model": "SDXL-1.0", "trigger_words": ["brickheadz"],
     "style_pack_ids": ["C02"], "asset_types": ["sprite"], "tool_affinity": ["sprite_gen"],
     "semantic_description": "LEGO Brickheadz toy style.",
     "quality_score": 3, "huggingface_downloads": 21},
    {"hf_repo": "artificialguybr/ToyRedmond-ToyLoraForSDXL10", "display_name": "Toy Redmond",
     "license": "creativeml-openrail-m", "base_model": "SDXL-1.0", "trigger_words": ["ToyRedmAF", "toy"],
     "style_pack_ids": ["C02"], "asset_types": ["sprite"], "tool_affinity": ["sprite_gen"],
     "semantic_description": "Toy/figurine render style.",
     "quality_score": 4, "huggingface_downloads": 42},
    {"hf_repo": "artificialguybr/ClayAnimationRedmond", "display_name": "Clay Animation Redmond",
     "license": "creativeml-openrail-m", "base_model": "SDXL-1.0", "trigger_words": ["Clay Animation"],
     "style_pack_ids": [], "asset_types": ["sprite"], "tool_affinity": ["sprite_gen"],
     "semantic_description": "Claymation stop-motion style.",
     "quality_score": 4, "huggingface_downloads": 27},
    # Retro / cinema
    {"hf_repo": "Norod78/SDXL-VintageMagStyle-Lora", "display_name": "Vintage Magazine Style",
     "license": "mit", "base_model": "SDXL-1.0", "trigger_words": ["vintage magazine"],
     "style_pack_ids": ["D07"], "asset_types": ["background"], "tool_affinity": ["background_gen"],
     "semantic_description": "Synthwave / 80s vintage magazine aesthetic.",
     "quality_score": 4, "huggingface_downloads": 103},
    {"hf_repo": "Norod78/SDXL-LofiGirl-Lora", "display_name": "Lofi Girl", "license": "mit",
     "base_model": "SDXL-1.0", "trigger_words": ["lofi girl"],
     "style_pack_ids": ["B04", "D05"], "asset_types": ["background"], "tool_affinity": ["background_gen"],
     "semantic_description": "Lofi cozy aesthetic backgrounds.",
     "quality_score": 4, "huggingface_downloads": 45},
    {"hf_repo": "artificialguybr/CINEMATIC-FILMSTILL-REDMOND-FLUXKLEIN9B", "display_name": "Cinematic Film Still",
     "license": "apache-2.0", "base_model": "FLUX.1-dev", "trigger_words": ["CinematicFilmstillAF"],
     "style_pack_ids": ["D04"], "asset_types": ["background"], "tool_affinity": ["background_gen"],
     "semantic_description": "Cinematic film-still backgrounds for cutscenes.",
     "quality_score": 4, "huggingface_downloads": 325},
    {"hf_repo": "artificialguybr/FILMGRAIN-REDMOND-FLUXKLEIN9B", "display_name": "Film Grain Redmond",
     "license": "apache-2.0", "base_model": "FLUX.1-dev", "trigger_words": ["filmgrain"],
     "style_pack_ids": ["A07", "B05"], "asset_types": ["background"], "tool_affinity": ["background_gen"],
     "semantic_description": "Film grain post-FX for horror/noir.",
     "quality_score": 4, "huggingface_downloads": 66},
    # Environment
    {"hf_repo": "artificialguybr/360Redmond", "display_name": "360 Redmond",
     "license": "bigscience-openrail-m", "base_model": "SDXL-1.0", "trigger_words": ["360 view"],
     "style_pack_ids": [], "asset_types": ["background"], "tool_affinity": ["background_gen"],
     "semantic_description": "360-degree panorama / skybox generation.",
     "quality_score": 4, "huggingface_downloads": 364},
    {"hf_repo": "artificialguybr/NebulRedmond", "display_name": "Nebula Redmond", "license": "openrail",
     "base_model": "SDXL-1.0", "trigger_words": ["nebula"],
     "style_pack_ids": ["C06"], "asset_types": ["background"], "tool_affinity": ["background_gen"],
     "semantic_description": "Space/nebula backgrounds for sci-fi.",
     "quality_score": 4, "huggingface_downloads": 34},
    {"hf_repo": "artificialguybr/ISOMETRIC-REDMOND-FLUXKLEIN9B", "display_name": "Isometric Redmond",
     "license": "apache-2.0", "base_model": "FLUX.1-dev", "trigger_words": ["isometric"],
     "style_pack_ids": [], "asset_types": ["tileset"],
     "genre_affinity": ["jrpg", "roguelike"], "tool_affinity": ["tileset_gen"],
     "semantic_description": "Isometric tilesets for JRPG/strategy.",
     "quality_score": 4, "huggingface_downloads": 30},
    # Paper / craft
    {"hf_repo": "Norod78/sdxl-PaperCutouts-Dreambooth", "display_name": "Paper Cutouts", "license": "mit",
     "base_model": "SDXL-1.0", "trigger_words": ["papercutouts"],
     "style_pack_ids": ["B06"], "asset_types": ["sprite"], "tool_affinity": ["sprite_gen"],
     "semantic_description": "Paper-craft cutout aesthetic.",
     "quality_score": 4, "huggingface_downloads": 30},
    {"hf_repo": "Norod78/SDXL-YarnArtStyle-LoRA", "display_name": "Yarn Art Style", "license": "openrail",
     "base_model": "SDXL-1.0", "trigger_words": ["yarn art"],
     "style_pack_ids": ["B06"], "asset_types": ["sprite", "background"], "tool_affinity": ["sprite_gen"],
     "semantic_description": "Yarn/fabric craft style.",
     "quality_score": 4, "huggingface_downloads": 49},
    {"hf_repo": "ostris/embroidery_style_lora_sdxl", "display_name": "Embroidery Style",
     "license": "apache-2.0", "base_model": "SDXL-1.0", "trigger_words": ["embroidery"],
     "style_pack_ids": ["B06"], "asset_types": ["tileset"], "tool_affinity": ["tileset_gen"],
     "semantic_description": "Embroidery/textile texture.",
     "quality_score": 4, "huggingface_downloads": 69},
    # Functional (icons / logo / sticker / UI)
    {"hf_repo": "artificialguybr/IconsRedmond-IconsLoraForSDXL-V2", "display_name": "Icons Redmond V2",
     "license": "creativeml-openrail-m", "base_model": "SDXL-1.0", "trigger_words": ["IconsRedmAF"],
     "style_pack_ids": [], "asset_types": ["icon"], "tool_affinity": ["ui_gen"],
     "semantic_description": "Game icons (inventory, abilities) generation.",
     "quality_score": 5, "huggingface_downloads": 64},
    {"hf_repo": "artificialguybr/LogoRedmond-LogoLoraForSDXL-V2", "display_name": "Logo Redmond V2",
     "license": "creativeml-openrail-m", "base_model": "SDXL-1.0", "trigger_words": ["LogoRedAF", "logo"],
     "style_pack_ids": [], "asset_types": ["logo"], "tool_affinity": ["ui_gen"],
     "semantic_description": "Game logo / title screen generation.",
     "quality_score": 5, "huggingface_downloads": 544},
    {"hf_repo": "artificialguybr/Logo-Redmond-FLUXKLEIN9B", "display_name": "Logo Redmond FLUX",
     "license": "apache-2.0", "base_model": "FLUX.1-dev", "trigger_words": ["logoredmaf"],
     "style_pack_ids": [], "asset_types": ["logo"], "tool_affinity": ["ui_gen"],
     "semantic_description": "Logo generation on FLUX (higher quality).",
     "quality_score": 5, "huggingface_downloads": 20},
    {"hf_repo": "artificialguybr/StickersRedmond", "display_name": "Stickers Redmond",
     "license": "creativeml-openrail-m", "base_model": "SDXL-1.0", "trigger_words": ["StickersRedmAF"],
     "style_pack_ids": [], "asset_types": ["sprite", "icon"], "tool_affinity": ["sprite_gen"],
     "genre_affinity": ["social_sim"],
     "semantic_description": "Sticker / emote sprite sheets.",
     "quality_score": 4, "huggingface_downloads": 129},
    {"hf_repo": "Norod78/SDXL-StickerSheet-Lora", "display_name": "Sticker Sheet", "license": "mit",
     "base_model": "SDXL-1.0", "trigger_words": ["sticker sheet"],
     "style_pack_ids": [], "asset_types": ["sprite"], "tool_affinity": ["sprite_gen"],
     "semantic_description": "Sticker-sheet style sprites.",
     "quality_score": 4, "huggingface_downloads": 57},
    {"hf_repo": "artificialguybr/ColoringBookRedmond-V2", "display_name": "Coloring Book V2",
     "license": "creativeml-openrail-m", "base_model": "SDXL-1.0", "trigger_words": ["ColoringBookAF"],
     "style_pack_ids": ["D03"], "asset_types": ["tileset", "sprite"], "tool_affinity": ["tileset_gen"],
     "semantic_description": "Line-art / coloring book base for outline sprites.",
     "quality_score": 5, "huggingface_downloads": 11552},
    {"hf_repo": "artificialguybr/StoryBookRedmond-V2", "display_name": "Storybook Redmond V2",
     "license": "creativeml-openrail-m", "base_model": "SDXL-1.0", "trigger_words": ["StoryBookAF"],
     "style_pack_ids": ["B06"], "asset_types": ["background"], "tool_affinity": ["background_gen"],
     "genre_affinity": ["visual_novel"],
     "semantic_description": "Illustrated storybook backgrounds for VN.",
     "quality_score": 4, "huggingface_downloads": 67},
    {"hf_repo": "artificialguybr/TshirtDesignRedmond-V2", "display_name": "T-shirt Design Redmond",
     "license": "creativeml-openrail-m", "base_model": "SDXL-1.0", "trigger_words": ["TShirtAF"],
     "style_pack_ids": [], "asset_types": ["sprite"], "tool_affinity": ["sprite_gen"],
     "semantic_description": "Flat merch/achievement graphics.",
     "quality_score": 4, "huggingface_downloads": 30},
    {"hf_repo": "goofyai/disney_style_xl", "display_name": "Disney Style XL", "license": "openrail",
     "base_model": "SDXL-1.0", "trigger_words": ["disney style"],
     "style_pack_ids": [], "asset_types": ["sprite"], "tool_affinity": ["sprite_gen"],
     "genre_affinity": ["social_sim"],
     "semantic_description": "Disney-style cartoon characters.",
     "quality_score": 4, "huggingface_downloads": 690},
]


# ============================================================
# REFERENCE_GAMES_DATA — 80 shipped games (concise mapping)
# Filled by 07_vision_moodboard with screenshot URLs + analysis
# ============================================================

def _ref(title, url, dev, year, style_packs, genres, engines, notes=""):
    return {
        "title": title, "store_url": url, "developer": dev,
        "release_year": year,
        "style_pack_tags": style_packs,
        "genre_tags": genres,
        "engine_compat": engines,
        "notable_features": [notes] if notes else [],
    }


REFERENCE_GAMES_DATA: list[dict] = [
    # Pixel 2D
    _ref("Hyper Light Drifter", "https://store.steampowered.com/app/257850/", "Heart Machine", 2016,
         ["A01"], ["action_2d"], ["godot", "monogame"], "Desaturated palette + neon accents"),
    _ref("Death's Door", "https://store.steampowered.com/app/894020/", "Acid Nerve", 2021,
         ["A01", "C01"], ["action_adventure"], ["godot"], "Top-down isometric pixel-3D hybrid"),
    _ref("Iconoclasts", "https://store.steampowered.com/app/393520/", "Joakim Sandberg", 2018,
         ["A01"], ["metroidvania"], ["godot", "monogame"], "Color saturated dark base"),
    _ref("Stardew Valley", "https://store.steampowered.com/app/413150/", "ConcernedApe", 2016,
         ["A02"], ["social_sim"], ["monogame"], "Warm cozy pixel art"),
    _ref("Eastward", "https://store.steampowered.com/app/977880/", "Pixpil", 2021,
         ["A02"], ["jrpg"], ["monogame", "godot"], "Cinematic pixel art high resolution"),
    _ref("Chicory: A Colorful Tale", "https://store.steampowered.com/app/1123450/", "Greg Lobanov", 2021,
         ["A02"], ["mobile_puzzle"], ["godot"], "Color-as-mechanic, dynamic palette"),
    _ref("A Short Hike", "https://store.steampowered.com/app/1055540/", "adamgryu", 2019,
         ["A02", "C01"], ["social_sim"], ["godot", "threejs"], "Pixel art hybrid low-poly 3D"),
    _ref("Downwell", "https://store.steampowered.com/app/360740/", "Moppin", 2015,
         ["A03"], ["browser_arcade"], ["godot"], "1-bit pixel, palette swap mechanic"),
    _ref("Minit", "https://store.steampowered.com/app/609490/", "JW + Kitty + Jukio", 2018,
         ["A03"], ["browser_arcade"], ["godot"], "1-bit minimal, 60-sec runs"),
    _ref("Return of the Obra Dinn", "https://store.steampowered.com/app/653530/", "Lucas Pope", 2018,
         ["A03"], ["visual_novel"], ["godot"], "Dithered 1-bit Macintosh-style"),
    _ref("World of Horror", "https://store.steampowered.com/app/913480/", "Panstasz", 2023,
         ["A03", "A07"], ["roguelike", "visual_novel"], ["godot"], "1-bit retro Mac horror"),
    _ref("Final Fantasy VI Pixel Remaster", "https://store.steampowered.com/app/1173820/", "Square Enix", 2022,
         ["A05"], ["jrpg"], ["monogame", "godot"], "SNES JRPG modern fidelity"),
    _ref("Chrono Trigger", "https://store.steampowered.com/app/613830/", "Square", 2018,
         ["A05"], ["jrpg"], ["monogame"], "SNES Akira Toriyama style"),
    _ref("Sea of Stars", "https://store.steampowered.com/app/1244090/", "Sabotage Studio", 2023,
         ["A05"], ["jrpg"], ["monogame", "godot"], "SNES-inspired modern lighting"),
    _ref("VA-11 Hall-A", "https://store.steampowered.com/app/447530/", "Sukeban Games", 2016,
         ["A06", "B04"], ["visual_novel"], ["renpy"], "Cyberpunk neon + anime sprite"),
    _ref("The Red Strings Club", "https://store.steampowered.com/app/589780/", "Deconstructeam", 2018,
         ["A06"], ["visual_novel"], ["renpy", "godot"], "Pixel cyberpunk noir"),
    _ref("Coffee Talk", "https://store.steampowered.com/app/914800/", "Toge Productions", 2020,
         ["A06", "B04"], ["visual_novel"], ["renpy"], "Lofi cyberpunk cozy"),
    _ref("Cloudpunk", "https://store.steampowered.com/app/746850/", "ION LANDS", 2020,
         ["A06", "C06"], ["threejs_showcase"], ["godot", "threejs"], "Voxel cyberpunk (3D)"),
    _ref("Lone Survivor", "https://store.steampowered.com/app/209830/", "Jasper Byrne", 2012,
         ["A07"], ["visual_novel"], ["godot"], "Pixel horror PSX-like"),
    _ref("Faith: Unholy Trinity", "https://store.steampowered.com/app/1043260/", "Airdorf", 2022,
         ["A07"], ["visual_novel"], ["godot"], "C64-style horror minimal"),
    _ref("Hotline Miami", "https://store.steampowered.com/app/219150/", "Dennaton", 2012,
         ["A08"], ["bullet_hell"], ["godot"], "Hyper neon top-down"),
    _ref("Hotline Miami 2", "https://store.steampowered.com/app/274170/", "Dennaton", 2015,
         ["A08", "D07"], ["bullet_hell"], ["godot"], "Synthwave + neon"),
    _ref("Nuclear Throne", "https://store.steampowered.com/app/242680/", "Vlambeer", 2015,
         ["A08"], ["roguelike", "bullet_hell"], ["godot"], "Pixel arcade neon roguelite"),
    _ref("Furi", "https://store.steampowered.com/app/423230/", "The Game Bakers", 2016,
         ["A08"], ["bullet_hell"], ["godot"], "Stylized neon boss rush"),
    _ref("GRIDD: Retroenhanced", "https://store.steampowered.com/app/559390/", "Antab Studio", 2017,
         ["A08", "D07"], ["browser_arcade"], ["godot", "threejs"], "Tron synthwave"),
    # Stylized 2D
    _ref("Monument Valley", "https://store.steampowered.com/app/1422510/", "ustwo games", 2022,
         ["B01"], ["mobile_puzzle"], ["defold", "phaser"], "Flat isometric pastel"),
    _ref("Alto's Adventure", "https://store.steampowered.com/app/440290/", "Snowman", 2018,
         ["B01"], ["mobile_puzzle", "browser_arcade"], ["defold", "phaser"], "Silhouette + gradient sky"),
    _ref("Donut County", "https://store.steampowered.com/app/702670/", "Ben Esposito", 2018,
         ["B01"], ["mobile_puzzle"], ["defold"], "Flat vector cute"),
    _ref("Mini Metro", "https://store.steampowered.com/app/287980/", "Dinosaur Polo Club", 2015,
         ["B01", "D06"], ["mobile_puzzle"], ["defold"], "Minimal flat geometric"),
    _ref("GRIS", "https://store.steampowered.com/app/683320/", "Nomada Studio", 2018,
         ["B02"], ["metroidvania"], ["godot"], "Watercolor + 2D art"),
    _ref("Hollow Knight", "https://store.steampowered.com/app/367520/", "Team Cherry", 2017,
         ["B02"], ["metroidvania"], ["godot"], "Hand-drawn dark fantasy"),
    _ref("Ori and the Blind Forest", "https://store.steampowered.com/app/261570/", "Moon Studios", 2015,
         ["B02"], ["metroidvania"], ["godot"], "Painted glow forest"),
    _ref("Spiritfarer", "https://store.steampowered.com/app/972660/", "Thunder Lotus", 2020,
         ["B02"], ["social_sim"], ["godot"], "Painted soft 2D"),
    _ref("Cuphead", "https://store.steampowered.com/app/268910/", "Studio MDHR", 2017,
         ["B03", "D02"], ["hardcore_platformer"], ["godot", "monogame"], "1930s rubber hose"),
    _ref("Borderlands 2", "https://store.steampowered.com/app/49520/", "Gearbox", 2012,
         ["B03"], ["multiplayer_arena"], ["godot"], "Comic cel-shading 3D"),
    _ref("Doki Doki Literature Club", "https://store.steampowered.com/app/698780/", "Team Salvato", 2017,
         ["B04"], ["visual_novel"], ["renpy"], "Anime soft VN"),
    _ref("Steins;Gate", "https://store.steampowered.com/app/412830/", "MAGES", 2014,
         ["B04", "D05"], ["visual_novel"], ["renpy"], "Anime + photo bg"),
    _ref("Genesis Noir", "https://store.steampowered.com/app/1310330/", "Feral Cat Den", 2021,
         ["B05"], ["visual_novel"], ["godot"], "Mono + jazz"),
    _ref("Mad Father", "https://store.steampowered.com/app/479660/", "Sen", 2022,
         ["B05", "A07"], ["visual_novel"], ["godot"], "Mono horror"),
    _ref("Paper Mario", "https://example.com/paper-mario", "Intelligent Sys", 2000,
         ["B06"], ["jrpg"], ["godot"], "Paper craft canonico (no Steam URL)"),
    # 3D
    _ref("Untitled Goose Game", "https://store.steampowered.com/app/837470/", "House House", 2019,
         ["C01"], ["social_sim"], ["godot", "threejs"], "Low-poly cute"),
    _ref("Lake", "https://store.steampowered.com/app/1812120/", "Gamious", 2021,
         ["C01"], ["social_sim"], ["godot"], "Low-poly warm"),
    _ref("Kind Words", "https://store.steampowered.com/app/1070710/", "Popcannibal", 2019,
         ["C01"], ["social_sim"], ["godot"], "Voxel + low-poly"),
    _ref("Cube World", "https://store.steampowered.com/app/1128000/", "Picroma", 2019,
         ["C02"], ["threejs_showcase"], ["threejs", "godot"], "Voxel cute"),
    _ref("Genshin Impact (reference)", "https://example.com/genshin", "HoYoverse", 2020,
         ["C03", "C07"], ["stride_action"], ["stride", "godot"], "Anime cel-shading 3D"),
    _ref("Tales of Arise", "https://store.steampowered.com/app/740130/", "Bandai Namco", 2021,
         ["C03"], ["stride_action"], ["stride"], "Anime cel-shading 3D"),
    _ref("Tunic", "https://store.steampowered.com/app/553420/", "Andrew Shouldice", 2022,
         ["C03", "C07"], ["stride_action"], ["godot", "stride"], "Cute toon 3D"),
    _ref("Crow Country", "https://store.steampowered.com/app/1996610/", "SFB Games", 2024,
         ["C04"], ["stride_action"], ["godot"], "PSX horror"),
    _ref("Signalis", "https://store.steampowered.com/app/1262350/", "rose-engine", 2022,
         ["C04"], ["stride_action"], ["godot"], "PSX inspired"),
    _ref("Mortuary Assistant", "https://store.steampowered.com/app/1295920/", "DarkStone", 2022,
         ["C04"], ["stride_action"], ["godot"], "PSX horror modern"),
    _ref("Lunark", "https://store.steampowered.com/app/1095830/", "Canari", 2023,
         ["C05"], ["hardcore_platformer"], ["godot"], "N64-inspired"),
    _ref("Yooka-Laylee", "https://store.steampowered.com/app/360830/", "Playtonic", 2017,
         ["C05"], ["stride_action"], ["godot", "stride"], "N64 spirit"),
    _ref("Mirror's Edge", "https://store.steampowered.com/app/17410/", "DICE", 2008,
         ["C06"], ["stride_action"], ["stride"], "Sci-fi clean minimalista"),
    _ref("Lightmatter", "https://store.steampowered.com/app/971890/", "Tunnel Vision", 2020,
         ["C06"], ["threejs_showcase"], ["threejs", "stride"], "Sci-fi clean"),
    _ref("The Talos Principle 2", "https://store.steampowered.com/app/835960/", "Croteam", 2023,
         ["C06"], ["stride_action"], ["stride"], "Sci-fi clean alta fedeltà"),
    _ref("Antichamber", "https://store.steampowered.com/app/219890/", "Alexander Bruce", 2013,
         ["C08"], ["threejs_showcase"], ["threejs"], "Abstract minimal"),
    _ref("Manifold Garden", "https://store.steampowered.com/app/473950/", "William Chyr", 2019,
         ["C08"], ["threejs_showcase"], ["threejs"], "Escher inspired"),
    _ref("Sayonara Wild Hearts", "https://store.steampowered.com/app/1115050/", "Simogo", 2019,
         ["C08", "D07"], ["browser_arcade"], ["threejs", "godot"], "Pop synth abstract"),
    # Experimental
    _ref("Dwarf Fortress", "https://store.steampowered.com/app/975370/", "Bay 12", 2022,
         ["D01"], ["roguelike"], ["love2d", "godot"], "ASCII + tileset opt"),
    _ref("Caves of Qud", "https://store.steampowered.com/app/333640/", "Freehold", 2024,
         ["D01"], ["roguelike"], ["love2d"], "ASCII rich"),
    _ref("Cogmind", "https://store.steampowered.com/app/722730/", "Grid Sage", 2017,
         ["D01"], ["roguelike"], ["love2d"], "ASCII modern"),
    _ref("Another World", "https://store.steampowered.com/app/233710/", "Éric Chahi", 2014,
         ["D02"], ["hardcore_platformer"], ["godot"], "Rotoscope vector"),
    _ref("Flashback", "https://store.steampowered.com/app/305920/", "Delphine", 2018,
         ["D02"], ["hardcore_platformer"], ["godot"], "Rotoscope sequel"),
    _ref("Frog Fractions", "https://store.steampowered.com/app/261720/", "Twinbeard", 2014,
         ["D03"], ["browser_arcade"], ["phaser"], "MS Paint deliberate"),
    _ref("Disco Elysium", "https://store.steampowered.com/app/632470/", "ZA/UM", 2019,
         ["D04"], ["visual_novel"], ["godot", "monogame"], "Painted realistic"),
    _ref("Ruined King", "https://store.steampowered.com/app/1500750/", "Airship", 2021,
         ["D04"], ["jrpg"], ["monogame"], "Painted high-res"),
    _ref("Pathologic 2", "https://store.steampowered.com/app/505230/", "Ice-Pick Lodge", 2019,
         ["D04"], ["stride_action"], ["godot"], "Painted gritty"),
    _ref("Pyre", "https://store.steampowered.com/app/462770/", "Supergiant", 2017,
         ["D04"], ["jrpg"], ["monogame"], "Painted vibrant"),
    _ref("Limbo", "https://store.steampowered.com/app/48000/", "Playdead", 2010,
         ["D06"], ["hardcore_platformer"], ["godot"], "Mono silhouette"),
    _ref("Thomas Was Alone", "https://store.steampowered.com/app/220780/", "Mike Bithell", 2012,
         ["D06"], ["mobile_puzzle"], ["godot"], "Mono rectangles"),
    _ref("A Dark Room", "https://store.steampowered.com/app/1029610/", "Doublespeak", 2017,
         ["D06"], ["visual_novel"], ["renpy"], "Mono text-based"),
    _ref("Far Cry 3 Blood Dragon", "https://store.steampowered.com/app/233270/", "Ubisoft", 2013,
         ["D07"], ["stride_action"], ["stride"], "Synthwave 80s parody"),
    _ref("Darkest Dungeon", "https://store.steampowered.com/app/262060/", "Red Hook", 2016,
         ["D08"], ["roguelike", "card_game"], ["monogame"], "Oil painted gothic"),
    _ref("Blasphemous", "https://store.steampowered.com/app/774361/", "The Game Kitchen", 2019,
         ["D08"], ["metroidvania"], ["monogame"], "Painted dark fantasy"),
    _ref("Salt and Sanctuary", "https://store.steampowered.com/app/283640/", "Ska Studios", 2016,
         ["D08"], ["metroidvania"], ["monogame"], "Painted dark"),
    _ref("Hades", "https://store.steampowered.com/app/1145360/", "Supergiant", 2020,
         ["B02", "D08"], ["roguelike"], ["godot"], "Painted action roguelite"),
    _ref("Dead Cells", "https://store.steampowered.com/app/588650/", "Motion Twin", 2018,
         ["A01"], ["roguelike", "metroidvania"], ["godot"], "Pixel art roguelite"),
    _ref("Celeste", "https://store.steampowered.com/app/504230/", "Maddy Makes Games", 2018,
         ["A01"], ["hardcore_platformer"], ["monogame"], "Pixel-perfect platformer"),
    _ref("Super Meat Boy", "https://store.steampowered.com/app/40800/", "Team Meat", 2010,
         ["A01"], ["hardcore_platformer"], ["monogame"], "Hardcore platformer"),
    _ref("N++", "https://store.steampowered.com/app/230270/", "Metanet", 2015,
         ["A03"], ["hardcore_platformer"], ["monogame"], "1-bit hardcore platformer"),
]
